repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pycqa/autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive, --max-line-length=80,
--indent-size=2]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=google, --line-length=80, --indent=2]

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: ["--style={based_on_style: pep8, COLUMN_LIMIT: 80, INDENT_WIDTH:
2}"]

  - repo: local
    hooks:
      - id: yaml-line-length
        name: YAML line length check
        entry: >
          bash -c 'for file in "$@"; do
            if [ -f "$file" ]; then
              awk "length > 80 {exit 1}" "$file" ||
                (echo "Line too long in $file"; exit 1);
            fi;
          done' --
        language: system
        types: [yaml]
        files: \.(yaml|yml)$
